name: CD

on:
  push:
    branches:
      - master

jobs:
  deploy_gh_pages:
    runs-on: ubuntu-latest
    steps:
      # checkout & yarn
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn --frozen-lockfile
      # build
      - run: npm run docs:build
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_branch: gh-pages
          build_dir: docs/.vuepress/dist
          jekyll: false
          fqdn: vuepress-plugin-flowchart-js.wxsm.space